config/routes.rb
SistemaVivero::Application.routes.draw do

  get "control/principal"

  resources :analisis
  resources :cultivos
  resources :medidas
  resources :estadisticas
  resources :reportes
  resources :sensor_viveros
  resources :sensors
  resources :viveros
  resources :asociar_cultivos
  resources :desasociar_cultivos
  resources :asociar_viveros
  resources :desasociar_viveros
  resources :asociar_sv_users
  resources :desasociar_sv_users
  
  devise_for :models
  devise_for :users

  post 'json/datos'
  post 'json/prueba'
  post 'json/prueba2'

   match ':controller(/:action(/:id))(.:format)'
root :to => "home#index"
end

app/models/sensor_vivero.rb
class SensorVivero < ActiveRecord::Base
  attr_accessible :descripcion, :ip, :luz_encendida, :nombre, :numero_serie, :riego_activo, :ventilacion_encendida, :cultivo_id, :estado_actualizado

  validates_uniqueness_of :numero_serie
  validates_presence_of :numero_serie
  validates_presence_of :nombre
  validates_presence_of :descripcion

  has_many :sensors
  belongs_to :cultivo

  has_many :perfil_user_sensor_viveros
  has_many :users, :through => :perfil_user_sensor_viveros
  has_many :perfils, :through => :perfil_user_sensor_viveros

end

app/controllers/sensor_viveros_controller.rb
class SensorViverosController < ApplicationController
  # GET /sensor_viveros
  # GET /sensor_viveros.json
  load_and_authorize_resource
  def index
    @sensor_viveros = current_user.sensor_viveros

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensor_viveros }
    end
  end

  # GET /sensor_viveros/1
  # GET /sensor_viveros/1.json
  def show
    @sensor_vivero = SensorVivero.find(params[:id])
    

    if !@sensor_vivero.users.include? current_user
      redirect_to sensor_viveros_path
      return
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor_vivero }
    end
  end

  # GET /sensor_viveros/new
  # GET /sensor_viveros/new.json
  def new
    @sensor_vivero = SensorVivero.new()


    if !@sensor_vivero.users.include? current_user
      redirect_to sensor_viveros_path
      return
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor_vivero }
    end
  end

  # GET /sensor_viveros/1/edit
  def edit
    @sensor_vivero = SensorVivero.find(params[:id])


    if !@sensor_vivero.users.include? current_user
      redirect_to sensor_viveros_path
      return
    end
  end

  # POST /sensor_viveros
  # POST /sensor_viveros.json
  def create
    @sensor_vivero = SensorVivero.new(params[:sensor_vivero])
    @sensor_vivero.luz_encendida = false
    @sensor_vivero.riego_activo = false
    @sensor_vivero.ventilacion_encendida = false

    @default_perfil = Perfil.where(perfil: 'Propietario').first

    @pus = PerfilUserSensorVivero.new(perfil: @default_perfil, user: current_user, sensor_vivero: @sensor_vivero)
    current_user.role = 'admin'

    respond_to do |format|
      if @sensor_vivero.save

        @pus.save
        current_user.save

        format.html { redirect_to @sensor_vivero, notice: 'Sensor vivero guardado correctamente.' }
        format.json { render json: @sensor_vivero, status: :created, location: @sensor_vivero }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor_vivero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensor_viveros/1
  # PUT /sensor_viveros/1.json
  def update
    @sensor_vivero = SensorVivero.find(params[:id])


    if !@sensor_vivero.users.include? current_user
      redirect_to sensor_viveros_path
      return
    end

    respond_to do |format|
      if @sensor_vivero.update_attributes(params[:sensor_vivero])
        format.html { redirect_to @sensor_vivero, notice: 'Sensor vivero guardado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor_vivero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensor_viveros/1
  # DELETE /sensor_viveros/1.json
  def destroy
    @sensor_vivero = SensorVivero.find(params[:id])


    if !@sensor_vivero.users.include? current_user
      redirect_to sensor_viveros_path
      return
    end
    
    users = @sensor_vivero.users

    puts "Recuperando usuarios asociados al sensor"
    #FIXME Si no se hace este puts no recupera bien los users... users es un array vacío.
    #Quizás sea mejor pasar el destroy abajo del todo y usar la query manual (comentada)
    puts users

    puts "Borrando sensor vivero..."
    @sensor_vivero.destroy

    users.each do |u|
      puts "Comprobando usuario #{u.id}"
      #  pus = PerfilUserSensorVivero.where("sensor_vivero_id != :svid AND user_id = :uid", {svid: @sensor_vivero.id, uid: u.id})
      pus = u.sensor_viveros

      if pus.empty?
        puts "El usuario #{u.id} pierde los privilegios de admin."
        u.update_attribute(:role, 'user')
      end
    end

    respond_to do |format|
      format.html { redirect_to sensor_viveros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sensor_viveros_helper.rb
module SensorViverosHelper
end

app/views/sensor_viveros/_form.html.erb
<%= form_for(@sensor_vivero) do |f| %>
<% if @sensor_vivero.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@sensor_vivero.errors.count, "error") %> impiden el guardado:</h2>

	<ul>
		<% @sensor_vivero.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :numero_serie, 'Número de serie:' %>
	<br />
	<%= f.text_field :numero_serie %>
</div>
<div class="field">
	<%= f.label :nombre %>
	<br />
	<%= f.text_field :nombre %>
</div>
<div class="field">
	<%= f.label :descripcion, 'Descripción' %>
	<br />
	<%= f.text_area :descripcion, :rows => 4, maxlength: 250 %>
</div>

<% if current_user.role == 'admin' %>
<!--
<div class="field">
<%= f.label :ip, 'IP' %>
<br />
<%= f.text_field :ip %>
</div>
-->
<%end%>

<div class="actions">
	<%= f.submit "Guardar", class: "btn btn-success" %>
</div>
<% end %>

app/views/sensor_viveros/edit.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Editar sensor_vivero</h1>

			<%= render 'form' %>

			
			<%= link_to 'Atrás', sensor_viveros_path %>
		</div>
	</div>
</div>

app/views/sensor_viveros/index.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>

			<div class="tabledeco">

				<table class="table">
					<thead>
						<tr class="tablehead">
							<th colspan="10">Sistemas SensorVivero Adquiridos</th>
						</tr>
						<tr>
							<th>Numero serie</th>
							<th>Nombre</th>
							<th>Descripcion</th>
							<th>IP</th>
							<th>Cultivo</th>
							<th>Estado confirmado</th>
							<th>Luz</th>
							<th>Riego</th>
							<th>Temperatura</th>
							<th class="width100">Operaciones</th>
						</tr>
					</thead>
					<tbody>
						<% @sensor_viveros.each do |sensor_vivero| %>
						<tr>
							<td class="td-center"><%= sensor_vivero.numero_serie %></td>
							<td><%= sensor_vivero.nombre %></td>
							<td><%= sensor_vivero.descripcion %></td>
							<td class="td-center"><%= sensor_vivero.ip %></td>
							<td><% if sensor_vivero.cultivo %><%= sensor_vivero.cultivo.nombre %><% end %></td>
							<td class="td-center"><% if sensor_vivero.estado_actualizado %>SI<% else%>NO<%end%></td>
							<td class="td-center"><% if sensor_vivero.luz_encendida %>ON<% else%> OFF<%end%></td>
							<td class="td-center"><% if sensor_vivero.riego_activo %>ON<% else%> OFF<%end%></td>
							<td class="td-center"><% if sensor_vivero.ventilacion_encendida %>ON<% else%> OFF<%end%></td>
							<td class="td-oper"><%= link_to image_tag("show.png",:alt => "Mostrar",:title => "Mostrar"), sensor_vivero %><%= link_to image_tag("edit.png",:alt => "Editar",:title => "Editar"), edit_sensor_vivero_path(sensor_vivero) %><%= link_to image_tag("delete.png",:alt => "Eliminar",:title => "Eliminar"), sensor_vivero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<br />
			<div>
				<%= button_to 'Nuevo', new_sensor_vivero_path,
				:class => "btn btn-primary", :style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Asociar sistema', asociar_cultivos_path,
				:class => "btn btn-warning",:style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Liberar sistema', desasociar_cultivos_path,
				:class => "btn btn-danger",:style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Dar permiso a usuario', asociar_sv_users_path,
				:class => "btn btn-warning",:style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Revocar permiso de usuario', desasociar_sv_users_path,
				:class => "btn btn-danger",:style => "float: left; margin-right: 10px;", :method => :get %>
			</div>
		</div>
	</div>

</div>

app/views/sensor_viveros/new.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Nuevo sensor vivero</h1>

			<%= render 'form' %>

			<% if current_user.role == 'admin' %>
			<%= link_to 'Atrás', sensor_viveros_path %>
			<%end%>
		</div>
	</div>
</div>

app/views/sensor_viveros/show.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>

			<p>
				<b>Numero serie:</b>
				<%= @sensor_vivero.numero_serie %>
			</p>

			<p>
				<b>Nombre:</b>
				<%= @sensor_vivero.nombre %>
			</p>

			<p>
				<b>Descripcion:</b>
				<%= @sensor_vivero.descripcion %>
			</p>

			<p>
				<b>Ip:</b>
				<%= @sensor_vivero.ip %>
			</p>

			<p>
				<b>Luz encendida:</b>
				<%= @sensor_vivero.luz_encendida %>
			</p>

			<p>
				<b>Riego activo:</b>
				<%= @sensor_vivero.riego_activo %>
			</p>

			<p>
				<b>Ventilacion encendida:</b>
				<%= @sensor_vivero.ventilacion_encendida %>
			</p>

			<%= button_to 'Editar', edit_sensor_vivero_path(@sensor_vivero) , :class => "btn btn-warning", :method => :get%> 
			<%= link_to 'Atrás', sensor_viveros_path %>

		</div>
	</div>
</div>