config/routes.rb
SistemaVivero::Application.routes.draw do

  get "control/principal"

  resources :analisis
  resources :cultivos
  resources :medidas
  resources :estadisticas
  resources :reportes
  resources :sensor_viveros
  resources :sensors
  resources :viveros
  resources :asociar_cultivos
  resources :desasociar_cultivos
  resources :asociar_viveros
  resources :desasociar_viveros
  resources :asociar_sv_users
  resources :desasociar_sv_users
  
  devise_for :models
  devise_for :users

  post 'json/datos'
  post 'json/prueba'
  post 'json/prueba2'

   match ':controller(/:action(/:id))(.:format)'
root :to => "home#index"
end

app/models/cultivo.rb
class Cultivo < ActiveRecord::Base
  attr_accessible :sensor_vivero_id,:co2_actual, :co2_maximo, 
  	:cosecha, :duracion_pulso_riego, :fotoperiodo, :funcionamiento, 
  	:humedad_actual, :humedad_maxima, :humedad_minima, 
  	:luz_actual, :luz_acumulada, :luz_limite,
  	 :maximos_pulsos_riego, :nombre, :ph_actual, :ph_maximo,
  	  :ph_minimo, :pulsos_riego_acumulados, :temperatura_actual, 
  	  :temperatura_maxima, :temperatura_minima, :vivero_id

#TODO inicializar maximo_pulsos_acumulados etc etc

  has_many :estadisticas
  has_many :reportes
  has_one :sensor_vivero
  belongs_to :vivero 

end

app/controllers/cultivos_controller.rb
class CultivosController < ApplicationController
  # GET /cultivos
  # GET /cultivos.json
  load_and_authorize_resource
  def index
    @cultivos = Cultivo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cultivos }
    end
  end

  # GET /cultivos/1
  # GET /cultivos/1.json
  def show
    @cultivo = Cultivo.find(params[:id])

   if !@cultivo.vivero.users.include? current_user
      redirect_to cultivos_path
      return
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cultivo }
    end
  end

  # GET /cultivos/new
  # GET /cultivos/new.json
  #Create a Culvito if there is a Vivero, if none exists redirected to a Vivero and news shows: 'Tiene que crear un vivero antes'
  def new
    @cultivo = Cultivo.new
    @viveros = current_user.viveros.map{ |x| [x.nombre, x.id]}
    puts @viveros
    respond_to do |format|
      if @viveros.any?
        format.html # new.html.erb
        format.json { render json: @cultivo }
      else
         format.html { redirect_to controller: :viveros, action: :new, notice: 'Tiene que crear un vivero antes'}
         format.json { render json: @cultivo }
      end
    end
  end

  # GET /cultivos/1/edit
  def edit
    @cultivo = Cultivo.find(params[:id])
    if !@cultivo.vivero.users.include? current_user
      redirect_to cultivos_path
      return
    end
    @viveros = current_user.viveros.map{ |x| [x.nombre, x.id]}
  end

  # POST /cultivos
  # POST /cultivos.json
  def create
    @cultivo = Cultivo.new(params[:cultivo])
    @cultivo.pulsos_riego_acumulados = 0

    respond_to do |format|
      if @cultivo.save
        format.html { redirect_to @cultivo, notice: 'Cultivo guardado correctamente.' }
        format.json { render json: @cultivo, status: :created, location: @cultivo }
      else
        format.html { render action: "new" }
        format.json { render json: @cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cultivos/1
  # PUT /cultivos/1.json
  def update
    @cultivo = Cultivo.find(params[:id])
   if !@cultivo.vivero.users.include? current_user
      redirect_to cultivos_path
      return
    end
    respond_to do |format|
      if @cultivo.update_attributes(params[:cultivo])
        format.html { redirect_to @cultivo, notice: 'Cultivo guardado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cultivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cultivos/1
  # DELETE /cultivos/1.json
  def destroy
    @cultivo = Cultivo.find(params[:id])
    if !@cultivo.vivero.users.include? current_user
      redirect_to cultivos_path
      return
    end
    @cultivo.destroy

    respond_to do |format|
      format.html { redirect_to cultivos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cultivos_helper.rb
module CultivosHelper
end

app/views/cultivos/_form.html.erb
<%= form_for(@cultivo) do |f| %>
<% if @cultivo.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@cultivo.errors.count, "error") %> prohibited this cultivo from being saved:</h2>

	<ul>
		<% @cultivo.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<%= f.label :nombre %>
	<br />
	<%= f.text_field :nombre %>
</div>
<div class="field">
	<%= f.label :vivero_id %>
	<br />
	<% if @cultivo.vivero %>
		<%= f.select :vivero_id, @viveros, :selected => @cultivo.vivero.id %>
   <% else %>
   		<%= f.select :vivero_id, @viveros %>
   <% end %>
</div>

<div class="field">
	<%= f.label :cosecha %>
	<br />
	<%= f.text_field :cosecha %>
</div>

<div class="actions">
	<%= f.submit "Guardar", class: "btn btn-success"%>
</div>
<% end %>

app/views/cultivos/edit.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Editar cultivo</h1>

			<%= render 'form' %>

			
			<%= link_to 'Atrás', cultivos_path %>

		</div>
	</div>
</div>

app/views/cultivos/index.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">

			<div class="tabledeco">

				<table class="table">
					<thead>
						<tr class="tablehead">
							<th colspan="22">Listado de cultivos</th>
						</tr>

						<tr>
							<th>Nombre</th>
							<th>Cosecha</th>
							<th>Func.</th>

							<th>Humedad</th>
							<th>Humedad Min</th>
							<th>Humedad Max</th>

							<th>Pulsos riego acumulados</th>
							<th>Duracion pulso riego</th>
							<th>Pulsos Riego Max</th>

							<th>Fotoperiodo</th>
							<th>Luz</th>
							<th>Luz acumulada</th>
							<th>Luz limite</th>

							<th>Temp.</th>
							<th>Temp. Min</th>
							<th>Temp. Max</th>

							<th>PH</th>
							<th>PH Min</th>
							<th>PH Max</th>

							<th>Co2</th>
							<th>Co2 Max</th>

							<th class="width100">Operaciones</th>
						</tr>
					</thead>

					<% @cultivos.each do |cultivo| %>
					<tr>
						<td><%= cultivo.nombre %></td>
						<td class="td-center"><%= cultivo.cosecha %></td>
						<td class="td-center"><%= cultivo.funcionamiento %></td>

						<td class="td-center"><%= cultivo.humedad_actual %></td>
						<td class="td-center"><%= cultivo.humedad_minima %></td>
						<td class="td-center"><%= cultivo.humedad_maxima %></td>

						<td class="td-center"><%= cultivo.pulsos_riego_acumulados %></td>
						<td class="td-center"><%= cultivo.duracion_pulso_riego %> </td>
						<td class="td-center"><%= cultivo.maximos_pulsos_riego %></td>

						<td class="td-center"><%= cultivo.fotoperiodo %></td>
						<td class="td-center"><%= cultivo.luz_actual %></td>
						<td class="td-center"><%= cultivo.luz_acumulada %></td>
						<td class="td-center"><%= cultivo.luz_limite %></td>

						<td class="td-center"><%= cultivo.temperatura_actual %></td>
						<td class="td-center"><%= cultivo.temperatura_minima %></td>
						<td class="td-center"><%= cultivo.temperatura_maxima %></td>

						<td class="td-center"><%= cultivo.ph_actual %></td>
						<td class="td-center"><%= cultivo.ph_minimo %></td>
						<td class="td-center"><%= cultivo.ph_maximo %></td>

						<td class="td-center"><%= cultivo.co2_actual %></td>
						<td class="td-center"><%= cultivo.co2_maximo %></td>

						<td class="td-oper"><%= link_to image_tag("show.png",:alt => "Mostrar",:title => "Mostrar"), cultivo %><%= link_to image_tag("edit.png",:alt => "Editar",:title => "Editar"), edit_cultivo_path(cultivo) %><%= link_to image_tag("delete.png",:alt => "Eliminar",:title => "Eliminar"), cultivo, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
					</tr>
					<% end %>
				</table>
			</div>
			<br />
			<%= button_to 'Nuevo', new_cultivo_path,
			:class => "btn btn-primary", :method => :get %>
		</div>
	</div>
</div>

app/views/cultivos/new.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Nuevo cultivo</h1>

			<%= render 'form' %>

			<%= link_to 'Atrás', cultivos_path %>
		</div>
	</div>
</div>

app/views/cultivos/show.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>

			<p>
				<b>Co2 actual:</b>
				<%= @cultivo.co2_actual %>
			</p>

			<p>
				<b>Co2 maximo:</b>
				<%= @cultivo.co2_maximo %>
			</p>

			<p>
				<b>Cosecha:</b>
				<%= @cultivo.cosecha %>
			</p>

			<p>
				<b>Fotoperiodo:</b>
				<%= @cultivo.fotoperiodo %>
			</p>

			<p>
				<b>Funcionamiento:</b>
				<%= @cultivo.funcionamiento %>
			</p>

			<p>
				<b>Humedad actual:</b>
				<%= @cultivo.humedad_actual %>
			</p>

			<p>
				<b>Humedad maxima:</b>
				<%= @cultivo.humedad_maxima %>
			</p>

			<p>
				<b>Humedad minima:</b>
				<%= @cultivo.humedad_minima %>
			</p>

			<p>
				<b>Luz actual:</b>
				<%= @cultivo.luz_actual %>
			</p>

			<p>
				<b>Luz acumulada:</b>
				<%= @cultivo.luz_acumulada %>
			</p>

			<p>
				<b>Luz limite:</b>
				<%= @cultivo.luz_limite %>
			</p>

			<p>
				<b>Maximos pulsos riego:</b>
				<%= @cultivo.maximos_pulsos_riego %>
			</p>

			<p>
				<b>Nombre:</b>
				<%= @cultivo.nombre %>
			</p>

			<p>
				<b>Ph actual:</b>
				<%= @cultivo.ph_actual %>
			</p>

			<p>
				<b>Ph maximo:</b>
				<%= @cultivo.ph_maximo %>
			</p>

			<p>
				<b>Ph minimo:</b>
				<%= @cultivo.ph_minimo %>
			</p>

			<p>
				<b>Pulsos riego acumulados:</b>
				<%= @cultivo.pulsos_riego_acumulados %>
			</p>

			<p>
				<b>Temperatura actual:</b>
				<%= @cultivo.temperatura_actual %>
			</p>

			<p>
				<b>Temperatura maxima:</b>
				<%= @cultivo.temperatura_maxima %>
			</p>

			<p>
				<b>Temperatura minima:</b>
				<%= @cultivo.temperatura_minima %>
			</p>

			<p>
				<b>Duracion pulso riego:</b>
				<%= @cultivo.duracion_pulso_riego %>
			</p>

			<%= button_to 'Editar', edit_cultivo_path(@cultivo) , :class => "btn btn-warning", :method => :get%>
			<%= link_to 'Atrás', cultivos_path %>
		</div>
	</div>
</div>