config/routes.rb
SistemaVivero::Application.routes.draw do

  get "control/principal"

  resources :analisis
  resources :cultivos
  resources :medidas
  resources :estadisticas
  resources :reportes
  resources :sensor_viveros
  resources :sensors
  resources :viveros
  resources :asociar_cultivos
  resources :desasociar_cultivos
  resources :asociar_viveros
  resources :desasociar_viveros
  resources :asociar_sv_users
  resources :desasociar_sv_users
  
  devise_for :models
  devise_for :users

  post 'json/datos'
  post 'json/prueba'
  post 'json/prueba2'

   match ':controller(/:action(/:id))(.:format)'
root :to => "home#index"
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :tipo, :sensor_vivero_id
  belongs_to :sensor_vivero
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  # GET /sensors
  # GET /sensors.json
  load_and_authorize_resource
  def index
    @sensors = Sensor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])
    # Si el sensor no pertenece al usuario
    if !@sensor.sensor_vivero.users.include? current_user
      redirect_to sensors_path
      return
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new
    @sensor_viveros = SensorVivero.all.map{|x| [x.nombre, x.id]}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])

     # Si el sensor no pertenece al usuario
    if !@sensor.sensor_vivero.users.include? current_user
      redirect_to sensors_path
      return
    end
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor guardado correctamente.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

     # Si el sensor no pertenece al usuario
    if !@sensor.sensor_vivero.users.include? current_user
      redirect_to sensors_path
      return
    end

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor guardado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])

     # Si el sensor no pertenece al usuario
    if !@sensor.sensor_vivero.users.include? current_user
      redirect_to sensors_path
      return
    end
    
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
<% if @sensor.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

	<ul>
		<% @sensor.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :tipo %>
	<br />
	<%= f.text_field :tipo %>
</div>

<div class="field">
	<%= f.label :sensor_vivero %>
	<br />
	<%= f.select :sensor_vivero_id, @sensor_viveros %>
</div>

<div class="actions">
	<%= f.submit "Guardar", class: "btn btn-success"%>
</div>
<% end %>

app/views/sensors/edit.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Editar sensor</h1>

			<%= render 'form' %>

			
			<%= link_to 'Atrás', sensors_path %>
		</div>
	</div>
</div>

app/views/sensors/index.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<div class="tabledeco">

				<table class="table">
					<thead>
						<tr class="tablehead">
							<th colspan="3">Listado de sensores</th>
						</tr>
						<tr>
							<th>Tipo</th>
							<th>Sistema</th>
							<th class="width100">Operaciones</th>
						</tr>
					</thead>
					<tbody>

						<% @sensors.each do |sensor| %>
						<tr>
							<td><%= sensor.tipo %></td>
							<td><%= sensor.sensor_vivero.nombre %></td>
							<td class="td-oper"><%= link_to image_tag("show.png",:alt => "Mostrar",:title => "Mostrar"), sensor %><%= link_to image_tag("edit.png",:alt => "Editar",:title => "Editar"), edit_sensor_path(sensor) %><%= link_to image_tag("delete.png",:alt => "Eliminar",:title => "Eliminar"), sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<br />

			<%= button_to 'Nuevo', new_sensor_path,
			:class => "btn btn-primary", :method => :get %>
		</div>
	</div>
</div>

app/views/sensors/new.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Nuevo sensor</h1>

			<%= render 'form' %>

			<%= link_to 'Atrás', sensors_path %>
		</div>
	</div>
</div>

app/views/sensors/show.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>

			<p>
				<b>Tipo:</b>
				<%= @sensor.tipo %>
			</p>

			<%= button_to 'Editar', edit_sensor_path(@sensor) , :class => "btn btn-warning", :method => :get%> 
			<%= link_to 'Atrás', sensors_path %>
		</div>
	</div>
</div>