config/routes.rb
SistemaVivero::Application.routes.draw do

  get "control/principal"

  resources :analisis
  resources :cultivos
  resources :medidas
  resources :estadisticas
  resources :reportes
  resources :sensor_viveros
  resources :sensors
  resources :viveros
  resources :asociar_cultivos
  resources :desasociar_cultivos
  resources :asociar_viveros
  resources :desasociar_viveros
  resources :asociar_sv_users
  resources :desasociar_sv_users
  
  devise_for :models
  devise_for :users

  post 'json/datos'
  post 'json/prueba'
  post 'json/prueba2'

   match ':controller(/:action(/:id))(.:format)'
root :to => "home#index"
end

app/models/vivero.rb
class Vivero < ActiveRecord::Base
  attr_accessible :nombre, :descripcion

  validates_uniqueness_of :nombre
  validates_presence_of :nombre
  validates_presence_of :descripcion
  
  has_many :cultivos
  has_and_belongs_to_many :users

end

app/controllers/viveros_controller.rb
class ViverosController < ApplicationController
  # GET /viveros
  # GET /viveros.json
  load_and_authorize_resource
  def index
    @viveros = current_user.viveros

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @viveros }
    end
  end

  # GET /viveros/1
  # GET /viveros/1.json
  def show
    @vivero = Vivero.find(params[:id])

    # Si el vivero no pertenece al usuario
    if !@vivero.users.include? current_user
      redirect_to viveros_path
      return
    end

    respond_to do |format|
     format.html # show.html.erb
      format.json { render json: @vivero }
    end

  end

  # GET /viveros/new
  # GET /viveros/new.json
  def new
    @vivero = Vivero.new()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vivero }
    end
  end

  # GET /viveros/1/edit
  def edit
    @vivero = Vivero.find(params[:id])

    # Si el vivero no pertenece al usuario
    if !@vivero.users.include? current_user
      redirect_to viveros_path
      return
    end

  end

  # POST /viveros
  # POST /viveros.json
  def create
    @vivero = Vivero.new(params[:vivero])

    @vivero.users << current_user
    
    respond_to do |format|
      if @vivero.save
        format.html { redirect_to @vivero, notice: 'Vivero guardado correctamente.' }
        format.json { render json: @vivero, status: :created, location: @vivero }
      else
        format.html { render action: "new" }
        format.json { render json: @vivero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /viveros/1
  # PUT /viveros/1.json
  def update
    @vivero = Vivero.find(params[:id])

    # Si el vivero no pertenece al usuario
    if !@vivero.users.include? current_user
      redirect_to viveros_path
      return
    end

    respond_to do |format|
      if @vivero.update_attributes(params[:vivero])
        format.html { redirect_to @vivero, notice: 'Vivero guardado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vivero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viveros/1
  # DELETE /viveros/1.json
  def destroy
    @vivero = Vivero.find(params[:id])

    # Si el vivero no pertenece al usuario
    if !@vivero.users.include? current_user
      redirect_to viveros_path
      return
    end
    
    @vivero.destroy

    respond_to do |format|
      format.html { redirect_to viveros_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/viveros_helper.rb
module ViverosHelper
end

app/views/viveros/_form.html.erb
<%= form_for(@vivero) do |f| %>
<% if @vivero.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@vivero.errors.count, "error") %> impiden el guardado:</h2>

	<ul>
		<% @vivero.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="field">
	<%= f.label :nombre %>
	<br />
	<%= f.text_field :nombre %>
</div>
<div class="field">
	<%= f.label :descripcion, 'Descripción' %>
	<br />
	<%= f.text_area :descripcion, :rows => 4, maxlength: 250 %>
</div>

<div class="actions">
	<%= f.submit "Guardar", class: "btn btn-success" %>
</div>
<% end %>

app/views/viveros/edit.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<h1>Editar vivero</h1>

			<%= render 'form' %>

			
			<%= link_to 'Atrás', viveros_path %>
		</div>
	</div>
</div>

app/views/viveros/index.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>

			<div class="tabledeco">
				<table class="table">
					<thead>
						<tr class="tablehead">
							<th colspan="3">Viveros</th>
						</tr>
						<tr>
							<th>Nombre</th>
							<th>Descripcion</th>
							<th class="width150">Operaciones</th>
						</tr>
					</thead>
					<tbody>
						<% @viveros.each do |vivero| %>
						<tr>
							<td><%= vivero.nombre %></td>
							<td><%= vivero.descripcion %></td>
							<td class="td-oper"><%= link_to image_tag("show.png",:alt => "Mostrar",:title => "Mostrar"), vivero %><%= link_to image_tag("edit.png",:alt => "Editar",:title => "Editar"), edit_vivero_path(vivero) %><%= link_to image_tag("delete.png",:alt => "Eliminar",:title => "Eliminar"), vivero, method: :delete, data: { confirm: 'Se eliminarán todos los cultivos de este vivero y se desasociarán de los sistemas en uso. ¿Está seguro?' } %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<br />
			<div style="min-width:38em">
				<%= button_to 'Nuevo', new_vivero_path,
				:class => "btn btn-primary", :style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Alta de Usuario en Vivero', asociar_viveros_path,
				:class => "btn btn-warning",:style => "float: left; margin-right: 10px;", :method => :get %>

				<%= button_to 'Baja de Usuario en Vivero', desasociar_viveros_path,
				:class => "btn btn-danger",:style => "float: left; margin-right: 10px;", :method => :get %>

			</div>
		</div>
	</div>

</div>

app/views/viveros/new.html.erb
<div class="datafield center borders">
	<% if params[:notice] %>
	<p class="notice" style="color: #FF0000" >
		<%= params[:notice] %>
	</p>
	<% end %>
	<div class="scroll">
		<div class="divcenter">
			<h1>Nuevo vivero</h1>

			<%= render 'form' %>

			<%= link_to 'Atrás', viveros_path %>

		</div>
	</div>
</div>

app/views/viveros/show.html.erb
<div class="datafield center borders">
	<div class="scroll">
		<div class="divcenter">
			<p id="notice">
				<%= notice %>
			</p>
			<p>
				<b>Nombre:</b>
				<%= @vivero.nombre %>
			</p>

			<p>
				<b>Descripcion:</b>
				<%= @vivero.descripcion %>
			</p>

			<%= button_to 'Editar', edit_vivero_path(@vivero) , :class => "btn btn-warning", :method => :get%> 
			<%= link_to 'Atrás', viveros_path %>

		</div>
	</div>
</div>